pullRequestOpened: >
  Thank you for opening this pull request, your code will be reviewed soon! 
  
  
  If any updates need to be made, I will leave a comment for you here outlining exactly what you need to change for your pull request to be accepted. 💖
  
  
  In the meantime, feel free to contribute to one of my other projects: 
  📚 EmojiPages - A listing of books and plays. (https://github.com/brittanyrw/emojipages)
  🎶 EmojiBops - A listing of songs. (https://github.com/brittanyrw/emojibops)
