pullRequestOpened: >
  Thank you for opening this pull request, we will review your code soon! 
  
  If any updates need to be made, we will leave a comment for you here outlining exactly what you need to change for your pull request to be accepted. 💖
