name: Greetings

on: [pull_request=]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Yay! Thanks for contributing to EmojiScreen for the first time. 💖 Your pull request will be reviewed as soon as possible. If you have any questions or would like to make updates to your PR, feel free to leave a comment in this pull request to let us know!'
